### PR TITLE
Implement Encoder and Decoder

### LINKED ISSUE #74: package has no decoder function to read from streams
Hi, I am wondering why this package doesn't provide a decoder to read from streams.  Would it be feasible to implement this?

### PR DESCRIPTION
**Pull request by SVilgelm**
add support for streaming encoding and decoding

closes #74 #71
solution is simpler that #59 was

### CODE REVIEW

**Comment by lavalamp** [comment]
@liggitt is the person you need.

**Comment by SVilgelm** [comment]
@liggitt Could you please review this PR?

**Comment by SVilgelm** [comment]
> (I should have mentioned, liggitt is OOO for a bit so please be patient)

thank you!

**Comment by liggitt** [comment]
Thanks for the PR. I'm back in the office now, but there are a few prereqs before I can get to this PR:
* I'm primarily focused on items for 1.25 design freeze this week
* Next is getting https://github.com/kubernetes-sigs/yaml/pull/76 in
* Finally, it's likely there will be an update to this library in service of https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2885-server-side-unknown-field-validation, and we want to make sure any streaming APIs are coherent with that

**Comment by SVilgelm** [comment]
thank you!
@liggitt may I ask you to drop a comment here, when all of those are done, so I can continue work on this feature?

**Comment by pmyjavec** [comment]
Curious what happened to this PR?

**Comment by SVilgelm** [comment]
Nothing special, lack of reviewers and the bot closed it automatically, I will reopen

**Pull request closed without merging**
