### PR TITLE
Fix lint for yaml_test.go

### PR DESCRIPTION
**Pull request by akram**
Fix lint for yaml_test.go

### CODE REVIEW

**Comment by maver1ck** [comment]
@liggitt 
Any chance to new release of kubernetes/yaml ?
Then we can upgrade it in dependent projects

**Comment by liggitt** [comment]
published https://github.com/kubernetes-sigs/yaml/releases/tag/v1.3.0

**Comment by akram** [comment]
awesome thanks @liggitt

**Pull request merged**
