### PR TITLE
upgrade gopkg.in/yaml.v2 to v2.2.8

### PR DESCRIPTION
**Pull request by BenTheElder**
https://github.com/kubernetes/kubernetes/pull/87637#issuecomment-580910083

### CODE REVIEW

**Comment by BenTheElder** [comment]
it would be nice to tag this and bump some consumers, not sure how that happens here
/assign @liggitt

**Comment by dims** [comment]
@BenTheElder `go mod vendor` please?

**Comment by BenTheElder** [comment]
ACK

**Pull request merged**
